name: pawon_ibu_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  shared_preferences: ^2.2.0
  supabase_flutter: ^1.10.8
  salomon_bottom_bar: ^3.3.2
  cupertino_icons: ^1.0.5
  smartrefresh: ^0.0.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  syncfusion_flutter_charts: ^22.2.8
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  easy_refresh: ^3.3.2+1
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  overlay_support: ^2.1.0
  url_launcher: ^6.1.12
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
